In [30]:
import numpy as np

In [31]:
a = np.arange(6)

In [32]:
a

array([0, 1, 2, 3, 4, 5])

In [33]:
b = np.array([1,2,34,3,4,0,5,6,7,567,9,7,7,457,56,76,56,7])
b = b.reshape(6, 3) # Reshape Your Function  According to given dimension

In [34]:
b

array([[  1,   2,  34],
       [  3,   4,   0],
       [  5,   6,   7],
       [567,   9,   7],
       [  7, 457,  56],
       [ 76,  56,   7]])

In [48]:
np.argsort(b, axis=0)

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3],
       [4, 3, 5],
       [5, 5, 0],
       [3, 4, 4]])

In [47]:
np.argsort(b).dtype

dtype('int64')

In [49]:
np.argsort(b, axis=0).dtype

dtype('int64')

In [42]:
np.argmin(b)

5

In [43]:
np.argmax(b)

9