## Basic Functions

In [1]:
import numpy as np
array1 = np.array([[3,2,6.5,7,7],[1,12,3,4,5]], dtype="int32")
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[[ 3  2  6  7  7]
 [ 1 12  3  4  5]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
print(np.ones(6))
np.ones(6).dtype

[1. 1. 1. 1. 1. 1.]


dtype('float64')

In [6]:
np.empty((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]], dtype=int32)

In [8]:
array1 ** 2

array([[  9,   4,  36,  49,  49],
       [  1, 144,   9,  16,  25]], dtype=int32)

In [9]:
array1+array1

array([[ 6,  4, 12, 14, 14],
       [ 2, 24,  6,  8, 10]], dtype=int32)

In [10]:
array1**array1

array([[        27,          4,      46656,     823543,     823543],
       [         1, -251658240,         27,        256,       3125]],
      dtype=int32)

In [11]:
print(np.array([12**12]))
np.array([12**12]).dtype

[8916100448256]


dtype('int64')

In [12]:
np.array([12.0**12], dtype="int32")

array([-251658240], dtype=int32)

In [13]:
1/array1

array([[0.33333333, 0.5       , 0.16666667, 0.14285714, 0.14285714],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

## Slicing

In [37]:
array2 = np.array([5, 4, 64, 3, 67, 88])

In [38]:
arr = array2[4:6].copy()

In [39]:
arr

array([67, 88])

In [40]:
arr[0] = 9

In [41]:
arr

array([ 9, 88])

In [42]:
array2

array([ 5,  4, 64,  3, 67, 88])

In [43]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]], dtype=int32)

In [44]:
array1[0, 3]

7